version: "3.3"

services:
  postgres:
    image: postgres:14-alpine
    restart: on-failure

    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "portfolio"

    ports:
      - "5433:5432"
